# Site settings
name: LanceLich
email: lichk51@gmail.com
author: LanceLich
url: http://www.lancelich.com
resume_site: http://www.lancelich.com/Resume.io/
github: https://github.com/LanceLich/
baseurl: ""
description: Play Hard
meta_description: Hello World
motto: Try it
banner: Try it again

#permalink: /:categories/:year/:month/:day/:title/
permalink: /:year/:month/:day/:title/
paginate: 10

exclude: ['README.md', 'Gemfile.lock', 'Gemfile', 'Rakefile']

github_username: LanceLich
highlighter: Pygments

# Build settings
markdown: kramdown

baidu_analysis: 94be4b0f9fc5d94cc0d0415ea6761ae9

FB:
  comments :
    provider : yungentie
